# Languages
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language (English)
en:
  languageCode: en-us
  languageName: English

# Japanese
ja:
  languageCode: ja
  languageName: 日本語
  contentDir: content/ja
